# Generated by Django 3.2.7 on 2021-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
