# Generated by Django 3.2.7 on 2021-09-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='replies',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.TextField(max_length=150),
        ),
    ]
